services:
  db_books_server:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=book
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    ports:
      - 4321:5432
    volumes:
      - db_book_server_volume:/var/lib/postgresql/data/

volumes:
  db_book_server_volume: