# Generated by Django 5.1.6 on 2025-02-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Book Name')),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=9, verbose_name='Book Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book/images/', verbose_name='Book Image')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
